imports:
    - { resource: config.yml }

framework:
    ide: "phpstorm://open?file=%%f&line=%%l"
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: %debug_toolbar%
    intercept_redirects: %debug_redirects%

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
            channels: "!event"
        console:
            type:   console
            bubble: false

swiftmailer:
    spool:
        type: file
        path: "%kernel.root_dir%/spool"
    delivery_address: %delivery_address%
