lah_admin:
    resource: "@LAHAdminBundle/Controller/"
    type:     annotation
    prefix:   /

lah_front:
    resource: "@LAHFrontBundle/Controller/"
    type:     annotation
    prefix:   /

lah_search:
    resource: "@LAHSearchBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
