services:
  lah.main.menu_builder:
      class: LAH\MainBundle\Menu\MenuBuilder
      arguments:
          - "@knp_menu.factory"
          - "@security.context"
          - ["pl"] # "%supported_locales%"

  lah.main.manager.car:
      class: LAH\MainBundle\Manager\CarManager
      arguments:
          - @doctrine.orm.default_entity_manager
          - LAH\MainBundle\Entity\Car
      calls:
          - [setRepositoryLocale, [@service_container]]

  lah.main.manager.color:
      class: LAH\MainBundle\Manager\ColorManager
      arguments:
          - @doctrine.orm.default_entity_manager
          - LAH\MainBundle\Entity\Color
      calls:
          - [setRepositoryLocale, [@service_container]]

  lah.main.twig_extension.instance_of:
      class: LAH\MainBundle\Twig\InstanceOfExtension
      tags:
          - { name: twig.extension }

  lah.main.twig_extension.revision:
      class: LAH\MainBundle\Twig\Revision
      calls:
        - [setRevisionFile, ["%revision_file%"]]
      tags:
          - { name: twig.extension }

  lah.main.twig_extension.html_description:
      class: LAH\MainBundle\Twig\HtmlDescription
      calls:
        - ["setLanguage", ["@=service('request').getLocale()"]]
        - ["setAddress", ["%company_address%"]]
      tags:
        - { name: twig.extension }

  lah.main.factory.type:
      class: LAH\MainBundle\Entity\Factory\TypeFactory
