services:
  front_bundle.menu_builder:
      class: Dende\FrontBundle\Menu\MenuBuilder
      arguments:
          - "@knp_menu.factory"
          - "@security.context"

  front_bundle.menu.lang:
      class: Knp\Menu\MenuItem
      factory_service: front_bundle.menu_builder
      factory_method: createLangMenu
      arguments: ["@request"]
      scope: request
      tags:
          - { name: knp_menu.menu, alias: langMenu }

  front_bundle.menu.main:
      class: Knp\Menu\MenuItem
      factory_service: front_bundle.menu_builder
      factory_method: createMainMenu
      arguments: ["@request"]
      scope: request
      tags:
          - { name: knp_menu.menu, alias: mainMenu }
