services:
    dende.front.manager.car:
        class: Dende\FrontBundle\Manager\CarManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - Dende\FrontBundle\Entity\Car
        calls:
            - [setRepositoryLocale, [@service_container]]

    dende.front.manager.color:
        class: Dende\FrontBundle\Manager\ColorManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - Dende\FrontBundle\Entity\Color
        calls:
            - [setRepositoryLocale, [@service_container]]

    dende.front.form.type.car:
        class: Dende\FrontBundle\Form\Type\CarType
        tags:
            - {name: form.type, alias: dende_form_add_car }

    dende.front.form.type.image:
        class: Dende\FrontBundle\Form\Type\ImageType
        tags:
            - {name: form.type, alias: dende_form_add_image }

#    front_bundle.menu_builder:
#        class: Dende\FrontBundle\Menu\MenuBuilder
#        arguments:
#            - "@knp_menu.factory"
#        calls:
#            - [setSocialLinks, [%social_links%]]
#
#    front_bundle.menu.lang:
#        class: Knp\Menu\MenuItem
#        factory_service: front_bundle.menu_builder
#        factory_method: createLangMenu
#        arguments: ["@request"]
#        scope: request
#        tags:
#            - { name: knp_menu.menu, alias: langMenu }
#
#    front_bundle.menu.main:
#        class: Knp\Menu\MenuItem
#        factory_service: front_bundle.menu_builder
#        factory_method: createMainMenu
#        scope: request
#        tags:
#            - { name: knp_menu.menu, alias: mainMenu }
#
#    front_bundle.menu.social:
#        class: Knp\Menu\MenuItem
#        factory_service: front_bundle.menu_builder
#        factory_method: createSocialMenu
#        scope: request
#        tags:
#            - { name: knp_menu.menu, alias: socialMenu }
#
#    front_bundle.locale_listener:
#        class: Dende\FrontBundle\Service\Listener\LocaleListener
#        arguments: ["%kernel.default_locale%"]
#        tags:
#            - { name: kernel.event_subscriber }



