imports:
    - { resource: forms.yml }
    - { resource: menus.yml }

services:
    dende.front.search_query_modifier:
      class: Dende\FrontBundle\Service\SearchQueryModifier

    dende.front.search_query_entity_merge:
      class: Dende\FrontBundle\Service\SearchQueryEntityMerge
      calls:
        - [setEntityManager, [@doctrine.orm.entity_manager]]

    dende.front.manager.car:
        class: Dende\FrontBundle\Manager\CarManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - Dende\FrontBundle\Entity\Car
        calls:
            - [setRepositoryLocale, [@service_container]]

    dende.front.manager.color:
        class: Dende\FrontBundle\Manager\ColorManager
        arguments:
            - @doctrine.orm.default_entity_manager
            - Dende\FrontBundle\Entity\Color
        calls:
            - [setRepositoryLocale, [@service_container]]

    dende.twig_extension.instance_of:
        class: Dende\FrontBundle\Twig\InstanceOfExtension
        tags:
            - { name: twig.extension }

    dende.twig_extension.revision:
        class: Dende\FrontBundle\Twig\Revision
        calls:
          - [setRevisionFile, ["%revision_file%"]]
        tags:
            - { name: twig.extension }

    dende.front.factory.type:
        class: Dende\FrontBundle\Entity\Factory\TypeFactory

    front_bundle.locale_listener:
        class: Dende\FrontBundle\Service\Listener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    front_bundle.listener.generate_thumbnail:
      class: Dende\FrontBundle\Event\Listener\GenerateThumbnailListener
      tags:
        - { name: doctrine.event_listener, event: uploadablePostFileProcess, method: onUploadPostFile }
