services:
    lah.front.form.type.search:
        class: LAH\FrontBundle\Form\Type\SearchType
        tags:
            - {name: form.type, alias: search }

    lah.front.form.type.car:
        class: LAH\FrontBundle\Form\Type\CarType
        calls:
          - [setLanguages, [%supported_locales%]]
        tags:
            - {name: form.type, alias: lah_form_car }

    lah.front.form.type.image:
        class: LAH\FrontBundle\Form\Type\ImageType
        tags:
            - {name: form.type, alias: lah_form_image }

    lah.front.form.type.color:
        class: LAH\FrontBundle\Form\Type\ColorType
        tags:
            - {name: form.type, alias: lah_form_color }

    lah.front.form.type.model:
        class: LAH\FrontBundle\Form\Type\ModelType
        tags:
            - {name: form.type, alias: lah_form_model }

    lah.front.form.type.price:
        class: LAH\FrontBundle\Form\Type\PriceType
        tags:
            - {name: form.type, alias: lah_form_price }

    lah.front.form.type.type:
        class: LAH\FrontBundle\Form\Type\TypeType
        tags:
            - {name: form.type, alias: lah_form_type }

    lah.front.form.type.title:
        class: LAH\FrontBundle\Form\Type\TitleType
        tags:
            - {name: form.type, alias: lah_form_title }

    lah.front.form.type.contact:
        class: LAH\FrontBundle\Form\Type\ContactType
        arguments: [@translator.default, @router]
        tags:
            - {name: form.type, alias: lah_form_contact }



    lah.front.form_handler.process_images:
        class: LAH\FrontBundle\Form\Handler\ProcessImages
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
            - [setUploadableManager, ["@stof_doctrine_extensions.uploadable.manager"]]

    lah.front.form_handler.process_types:
        class: LAH\FrontBundle\Form\Handler\ProcessType
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    lah.front.form_handler.process_colors:
        class: LAH\FrontBundle\Form\Handler\ProcessColor
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    lah.front.form_handler.process_models:
        class: LAH\FrontBundle\Form\Handler\ProcessModel
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    lah.front.form_handler.process_prices:
        class: LAH\FrontBundle\Form\Handler\ProcessPrices
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    lah.front.form_handler.car:
      class: LAH\FrontBundle\Form\Handler\CarFormHandler
      calls:
        - [setProcessColors, ["@lah.front.form_handler.process_colors"]]
        - [setProcessModels, ["@lah.front.form_handler.process_models"]]
        - [setProcessTypes, ["@lah.front.form_handler.process_types"]]
        - [setProcessImages, ["@lah.front.form_handler.process_images"]]
        - [setProcessPrices, ["@lah.front.form_handler.process_prices"]]
