services:
  lah.front.locale_listener:
    class: LAH\FrontBundle\Service\Listener\LocaleListener
    arguments: ["%kernel.default_locale%"]
    tags:
        - { name: kernel.event_subscriber }

  lah.front.form.type.contact:
    class: LAH\FrontBundle\Form\Type\ContactType
    arguments: [@translator.default, @router]
    tags:
        - {name: form.type, alias: lah_contact }

  lah.front.menu.lang:
    class: Knp\Menu\MenuItem
    factory_service: lah.main.menu_builder
    factory_method: createLangMenu
    arguments: ["@request"]
    scope: request
    tags:
      - { name: knp_menu.menu, alias: langMenu }

  lah.front.menu.front:
    class: Knp\Menu\MenuItem
    factory_service: lah.main.menu_builder
    factory_method: createFrontMenu
    arguments: ["@request"]
    scope: request
    tags:
      - { name: knp_menu.menu, alias: frontMenu }
